const products = [
  {
    category: "Jewelery",
    id: 1,
    brand: "Nagasaki",
    price: 405,
    product_name: "Dragon Ring",
    title: "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
    image: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    stock: 10,
    offer: 20,
    
  },
  {
    category: "Jewelery",
    id: 2,
    brand: "EXPCO",
    price: 405,
    product_name: "Georgeous Silver Ring",
    title:  "White Gold Plated Princess",
    image: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
    stock: 10,
    offer: 20,
  },
  {
    category: "Electronics",
    id: 3,
    brand: "Samsung",
    price: 105,
    product_name: "PC Memory",
    image: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    stock: 10,
    offer: 20,
  },
  {
    category: "Electronics",
    id: 4,
    brand: "Samsung",
    price: 405,
    product_name: "Tv 49-Inch",
    title: "Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED ",
    image: "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
    stock: 10,
    offer: false,
  },
  {
    category: "T-shirts",
    id: 5,
    brand: "AE",
    price: 45,
    title: "Mens Casual Slim Fit",
    image: "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    product_name: "Long Sleve Shirt",
    stock: 10,
    offer: false,
  },
  {
    category: "T-shirts",
    id: 6,
    brand: "Chanel",
    price: 30,
    title: "Mens Casual Premium Slim Fit T-Shirts ",
    product_name: "Blue Sweater",
    image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
    stock: 0,
    offer: 30,
  },
];



export default products;
